import type { Icon } from "@phosphor-icons/react";
import {
  ArchiveIcon,
  ArticleIcon,
  ArrowSquareOutIcon,
  BookOpenIcon,
  BriefcaseIcon,
  CaretDownIcon,
  CheckCircleIcon,
  CirclesFourIcon,
  ClockIcon,
  CloudArrowUpIcon,
  CodeIcon,
  DesktopTowerIcon,
  FileTextIcon,
  GithubLogoIcon,
  HeartIcon,
  ImagesIcon,
  MagnifyingGlassIcon,
  MoonIcon,
  PaletteIcon,
  PencilSimpleIcon,
  ShieldCheckIcon,
  SparkleIcon,
  SunIcon,
  TrayIcon,
  UserIcon,
  UsersIcon,
} from "@phosphor-icons/react";
import type { NavItem } from "../data/admin";

export const iconForNav: Record<NavItem["icon"], Icon> = {
  inbox: TrayIcon,
  work: BriefcaseIcon,
  content: ArticleIcon,
  life: HeartIcon,
  knowledge: BookOpenIcon,
  search: UsersIcon,
  system: CirclesFourIcon,
  fleet: DesktopTowerIcon,
  deploy: CloudArrowUpIcon,
  repo: GithubLogoIcon,
  proof: ShieldCheckIcon,
  handoff: ArrowSquareOutIcon,
  edit: PencilSimpleIcon,
  review: CheckCircleIcon,
  draft: FileTextIcon,
  media: ImagesIcon,
  newsletter: ArticleIcon,
  health: HeartIcon,
  aesthetics: PaletteIcon,
};

export {
  ArchiveIcon,
  ArrowSquareOutIcon,
  CaretDownIcon,
  CheckCircleIcon,
  ClockIcon,
  CodeIcon,
  MagnifyingGlassIcon,
  MoonIcon,
  SparkleIcon,
  SunIcon,
  UserIcon,
};
