name = "anipotts-www"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
account_id = "0f856093bdcd34a7da1bde5ee4385163"

# D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "anipotts-db"
database_id = "a8aadf73-bbf4-447c-97db-cb3e50b4e26f"
