-- 0028_seed_listing_content_review_operations.sql
-- Seed inert admin review operations for D1-backed listing page copy.
--
-- These rows make newer page_content-backed public routes visible in the
-- D1-backed content review queue. They do not insert published content records,
-- edit page_content, add save APIs, publish, send, deploy, or mutate external
-- services.
--
-- Rollback:
--   DELETE FROM content_draft_operations
--   WHERE operation_id IN (
--     'content-draft-making-index-copy-2026-06-29',
--     'content-draft-projects-index-copy-2026-06-29',
--     'content-draft-writing-index-copy-2026-06-29',
--     'content-draft-newsletter-archive-copy-2026-06-29',
--     'content-draft-orchestrating-hero-copy-2026-06-29'
--   );

INSERT OR IGNORE INTO content_draft_operations (
  operation_id,
  kind,
  surface,
  route,
  source_ref,
  field_path,
  current_value_ref,
  proposed_value,
  status,
  risk_level,
  authority_state,
  required_approval_ids,
  allowed_actions,
  forbidden_actions,
  preview_targets,
  proof_ids,
  evidence_uri,
  redaction,
  created_by,
  created_at,
  updated_at,
  expires_at,
  rollback_ref,
  reviewer_note,
  metadata
) VALUES (
  'content-draft-making-index-copy-2026-06-29',
  'content_draft',
  'public_site',
  '/making',
  'D1 page_content:making, fallback @anipotts/lib/cms DEFAULT_MAKING_INDEX_CONTENT',
  'projects.making_index_copy',
  'published_page_content:making',
  'Review future edits to the /making title, meta description, hero title, and hero summary through preview-only operations before any save path edits page_content.',
  'previewed',
  'low',
  'page_content_preview_only_no_write',
  '[]',
  '["render_preview","request_review"]',
  '["save","publish","deploy","rewrite_source","sync_external"]',
  '["/content/review","/content/preview","/making"]',
  '["content.projects.index.page-content","admin.content.preview.d1"]',
  'repo://apps/www/src/pages/making.astro',
  'public_copy_only',
  'agent',
  '2026-06-29T00:00:00Z',
  '2026-06-29T00:00:00Z',
  '2026-07-29T00:00:00Z',
  'published_page_content:making',
  'Seeded as an inert review operation. No content record, page_content write, source edit, or publish event is created.',
  '{"source":"drizzle/migrations/0028_seed_listing_content_review_operations.sql","write_path":"inactive"}'
);

INSERT OR IGNORE INTO content_draft_operations (
  operation_id,
  kind,
  surface,
  route,
  source_ref,
  field_path,
  current_value_ref,
  proposed_value,
  status,
  risk_level,
  authority_state,
  required_approval_ids,
  allowed_actions,
  forbidden_actions,
  preview_targets,
  proof_ids,
  evidence_uri,
  redaction,
  created_by,
  created_at,
  updated_at,
  expires_at,
  rollback_ref,
  reviewer_note,
  metadata
) VALUES (
  'content-draft-projects-index-copy-2026-06-29',
  'content_draft',
  'public_site',
  '/projects',
  'D1 page_content:projects, fallback @anipotts/lib/cms DEFAULT_PROJECTS_INDEX_CONTENT',
  'projects.archive_index_copy',
  'published_page_content:projects',
  'Review future edits to the /projects title, meta description, hero title, hero summary, and making link through preview-only operations before any save path edits page_content.',
  'previewed',
  'low',
  'page_content_preview_only_no_write',
  '[]',
  '["render_preview","request_review"]',
  '["save","publish","deploy","rewrite_source","sync_external"]',
  '["/content/review","/content/preview","/projects"]',
  '["content.projects.archive-index.page-content","admin.content.preview.d1"]',
  'repo://apps/www/src/pages/projects/index.astro',
  'public_copy_only',
  'agent',
  '2026-06-29T00:00:00Z',
  '2026-06-29T00:00:00Z',
  '2026-07-29T00:00:00Z',
  'published_page_content:projects',
  'Seeded as an inert review operation. No content record, page_content write, source edit, or publish event is created.',
  '{"source":"drizzle/migrations/0028_seed_listing_content_review_operations.sql","write_path":"inactive"}'
);

INSERT OR IGNORE INTO content_draft_operations (
  operation_id,
  kind,
  surface,
  route,
  source_ref,
  field_path,
  current_value_ref,
  proposed_value,
  status,
  risk_level,
  authority_state,
  required_approval_ids,
  allowed_actions,
  forbidden_actions,
  preview_targets,
  proof_ids,
  evidence_uri,
  redaction,
  created_by,
  created_at,
  updated_at,
  expires_at,
  rollback_ref,
  reviewer_note,
  metadata
) VALUES (
  'content-draft-writing-index-copy-2026-06-29',
  'content_draft',
  'public_site',
  '/writing',
  'D1 page_content:writing, fallback @anipotts/lib/cms DEFAULT_WRITING_INDEX_CONTENT',
  'writing.index_copy',
  'published_page_content:writing',
  'Review future edits to the /writing title, meta description, hero summary, and search placeholder through preview-only operations before any save path edits page_content.',
  'previewed',
  'low',
  'page_content_preview_only_no_write',
  '[]',
  '["render_preview","request_review"]',
  '["save","publish","deploy","rewrite_source","sync_external"]',
  '["/content/review","/content/preview","/writing"]',
  '["content.writing.index.page-content","admin.content.preview.d1"]',
  'repo://apps/www/src/pages/writing/index.astro',
  'public_copy_only',
  'agent',
  '2026-06-29T00:00:00Z',
  '2026-06-29T00:00:00Z',
  '2026-07-29T00:00:00Z',
  'published_page_content:writing',
  'Seeded as an inert review operation. No content record, page_content write, source edit, newsletter send, or publish event is created.',
  '{"source":"drizzle/migrations/0028_seed_listing_content_review_operations.sql","write_path":"inactive"}'
);

INSERT OR IGNORE INTO content_draft_operations (
  operation_id,
  kind,
  surface,
  route,
  source_ref,
  field_path,
  current_value_ref,
  proposed_value,
  status,
  risk_level,
  authority_state,
  required_approval_ids,
  allowed_actions,
  forbidden_actions,
  preview_targets,
  proof_ids,
  evidence_uri,
  redaction,
  created_by,
  created_at,
  updated_at,
  expires_at,
  rollback_ref,
  reviewer_note,
  metadata
) VALUES (
  'content-draft-newsletter-archive-copy-2026-06-29',
  'content_draft',
  'newsletter',
  '/newsletter/archive',
  'D1 page_content:newsletter_archive, fallback @anipotts/lib/cms DEFAULT_NEWSLETTER_ARCHIVE_CONTENT',
  'newsletter.archive_copy',
  'published_page_content:newsletter_archive',
  'Review future edits to the /newsletter/archive title, meta description, section label, hero title, and hero summary through preview-only operations before any save path edits page_content.',
  'previewed',
  'low',
  'page_content_preview_only_no_write',
  '[]',
  '["render_preview","request_review"]',
  '["save","publish","send","schedule","sync_provider"]',
  '["/content/review","/content/preview","/newsletter/archive"]',
  '["content.newsletter.archive.page-content","admin.content.preview.d1"]',
  'repo://apps/www/src/pages/newsletter/archive.astro',
  'public_copy_only',
  'agent',
  '2026-06-29T00:00:00Z',
  '2026-06-29T00:00:00Z',
  '2026-07-29T00:00:00Z',
  'published_page_content:newsletter_archive',
  'Seeded as an inert review operation. No content record, page_content write, provider sync, send, or publish event is created.',
  '{"source":"drizzle/migrations/0028_seed_listing_content_review_operations.sql","write_path":"inactive"}'
);

INSERT OR IGNORE INTO content_draft_operations (
  operation_id,
  kind,
  surface,
  route,
  source_ref,
  field_path,
  current_value_ref,
  proposed_value,
  status,
  risk_level,
  authority_state,
  required_approval_ids,
  allowed_actions,
  forbidden_actions,
  preview_targets,
  proof_ids,
  evidence_uri,
  redaction,
  created_by,
  created_at,
  updated_at,
  expires_at,
  rollback_ref,
  reviewer_note,
  metadata
) VALUES (
  'content-draft-orchestrating-hero-copy-2026-06-29',
  'content_draft',
  'public_site',
  '/orchestrating',
  'D1 page_content:orchestrating, fallback @anipotts/lib/cms DEFAULT_ORCHESTRATING_CONTENT',
  'orchestrating.hero_copy',
  'published_page_content:orchestrating',
  'Review future edits to the /orchestrating hero and live-session panel copy through preview-only operations before any save path edits page_content.',
  'previewed',
  'medium',
  'page_content_preview_only_no_write',
  '[]',
  '["render_preview","request_review"]',
  '["save","publish","deploy","rewrite_source","sync_external"]',
  '["/content/review","/content/preview","/orchestrating"]',
  '["content.orchestrating.hero.page-content","admin.content.preview.d1"]',
  'repo://apps/www/src/pages/orchestrating.astro',
  'public_copy_only',
  'agent',
  '2026-06-29T00:00:00Z',
  '2026-06-29T00:00:00Z',
  '2026-07-29T00:00:00Z',
  'published_page_content:orchestrating',
  'Seeded as an inert review operation. No content record, page_content write, source edit, or publish event is created.',
  '{"source":"drizzle/migrations/0028_seed_listing_content_review_operations.sql","write_path":"inactive"}'
);
