import {
  WORK_LIFECYCLE_SCHEMA_VERSION,
  type WorkLifecycleSnapshot,
} from "./work-lifecycle";

const NOW = "2026-07-22T16:00:00.000Z";

export const fixtureWorkLifecycle: WorkLifecycleSnapshot = {
  schema_version: WORK_LIFECYCLE_SCHEMA_VERSION,
  generated_at: NOW,
  source_mode: "fixture",
  adapter_version: "fixture-v1",
  sources: [
    {
      source_id: "source-codex-admin-home",
      surface: "codex",
      provider: "openai-codex",
      account_scope: "ani-personal",
      native_id: "task-admin-home",
      host: "ap-pro",
      locator: "codex://task/admin-home",
      title: "admin home lifecycle build",
      summary:
        "repository implementation and local proof for the canonical admin home.",
      project: "anipotts-com",
      cwd: "/Users/anipotts/Code/projects/anipotts-com",
      native_status: "active",
      native_runtime: "running",
      goal: "ship one reviewable local lifecycle slice",
      content_hash: "sha256:codex-admin-home-v1",
      imported_at: NOW,
      reconciled_at: NOW,
      reconciliation_state: "fresh",
      import_state: "updated",
      lineage_refs: ["handoff:2026-07-22-admin-home-conversation-lifecycle"],
      proof_refs: ["git:branch/codex-pro-admin-home-lifecycle"],
      privacy: "sanitized",
    },
    {
      source_id: "source-chatgpt-lifecycle-export",
      surface: "chatgpt_export",
      provider: "openai-chatgpt-export",
      account_scope: "ani-personal",
      native_id: "conversation-lifecycle-planning",
      host: null,
      locator: "chatgpt-export://conversation/lifecycle-planning",
      title: "conversation lifecycle planning",
      summary:
        "product decisions for converging conversations on shared work entities.",
      project: "anipotts-com",
      cwd: null,
      native_status: "exported",
      native_runtime: "closed",
      goal: null,
      content_hash: "sha256:chatgpt-lifecycle-v1",
      imported_at: "2026-07-21T22:00:00.000Z",
      reconciled_at: "2026-07-22T15:55:00.000Z",
      reconciliation_state: "fresh",
      import_state: "duplicate",
      lineage_refs: ["codex://task/admin-home"],
      proof_refs: ["export:sha256-redacted"],
      privacy: "sanitized",
    },
    {
      source_id: "source-github-pr-244",
      surface: "github",
      provider: "github",
      account_scope: "anipotts/anipotts.com",
      native_id: "pull/244",
      host: "github.com",
      locator: "https://github.com/anipotts/anipotts.com/pull/244",
      title: "superseded admin control plane",
      summary: "preserved implementation inventory used as reference only.",
      project: "anipotts-com",
      cwd: null,
      native_status: "closed",
      native_runtime: "closed",
      goal: null,
      content_hash: "git:30976f0",
      imported_at: "2026-07-20T18:00:00.000Z",
      reconciled_at: "2026-07-22T15:55:00.000Z",
      reconciliation_state: "fresh",
      import_state: "updated",
      lineage_refs: ["git:30976f0"],
      proof_refs: ["git:tag/preserve-admin-244-30976f0-20260720"],
      privacy: "sanitized",
    },
    {
      source_id: "source-infra-adapter-handoff",
      surface: "handoff",
      provider: "infra-handoff",
      account_scope: "chief-infra",
      native_id: "admin-lifecycle-adapter-v1",
      host: "ap-pro",
      locator: "handoff://chief-infra/admin-lifecycle-adapter-v1",
      title: "infra adapter contract",
      summary:
        "versioned sanitized adapter seam awaiting final fixture parity.",
      project: "infra",
      cwd: "/Users/anipotts/Infra",
      native_status: "blocked",
      native_runtime: "blocked",
      goal: "settle immutable export and supported codex metadata shapes",
      content_hash: "sha256:infra-adapter-partial",
      imported_at: "2026-07-22T15:30:00.000Z",
      reconciled_at: "2026-07-22T15:30:00.000Z",
      reconciliation_state: "partial",
      import_state: "updated",
      lineage_refs: ["handoff:chief-infra"],
      proof_refs: [],
      privacy: "sanitized",
    },
    {
      source_id: "source-retired-topology-handoff",
      surface: "handoff",
      provider: "infra-handoff",
      account_scope: "anipotts-com",
      native_id: "2026-07-17-four-task-topology",
      host: "ap-pro",
      locator: "handoff://anipotts-com/retired-four-task-topology",
      title: "retired four-task site topology",
      summary: "historical ownership map retained as searchable evidence.",
      project: "anipotts-com",
      cwd: null,
      native_status: "historical",
      native_runtime: "closed",
      goal: null,
      content_hash: "sha256:retired-topology-v1",
      imported_at: "2026-07-20T18:00:00.000Z",
      reconciled_at: "2026-07-22T15:55:00.000Z",
      reconciliation_state: "fresh",
      import_state: "updated",
      lineage_refs: ["handoff:2026-07-20-anipotts-com-consolidation"],
      proof_refs: ["handoff:2026-07-17-anipotts-com-four-task-topology"],
      privacy: "sanitized",
    },
    {
      source_id: "source-unavailable-legacy-index",
      surface: "admin",
      provider: "admin-local-index",
      account_scope: "anipotts-com",
      native_id: "legacy-local-index",
      host: "ap-mini",
      locator: "admin://source/legacy-local-index",
      title: "legacy local index probe",
      summary: "source identity is known but the latest adapter read failed.",
      project: "anipotts-com",
      cwd: null,
      native_status: "unavailable",
      native_runtime: "unknown",
      goal: null,
      content_hash: "sha256:legacy-index-last-good",
      imported_at: "2026-07-19T12:00:00.000Z",
      reconciled_at: "2026-07-22T15:40:00.000Z",
      reconciliation_state: "unavailable",
      import_state: "failed",
      lineage_refs: [],
      proof_refs: ["probe:read-failed"],
      privacy: "sanitized",
    },
    {
      source_id: "source-conflicting-archive-record",
      surface: "admin",
      provider: "admin-local-index",
      account_scope: "anipotts-com",
      native_id: "conflicting-archive-record",
      host: "ap-mini",
      locator: "admin://source/conflicting-archive-record",
      title: "conflicting archive record",
      summary:
        "two sanitized inventory snapshots disagree on completion state.",
      project: "anipotts-com",
      cwd: null,
      native_status: "conflicting",
      native_runtime: "closed",
      goal: null,
      content_hash: "sha256:conflicting-archive-record",
      imported_at: "2026-07-21T12:00:00.000Z",
      reconciled_at: "2026-07-22T15:40:00.000Z",
      reconciliation_state: "conflicting",
      import_state: "updated",
      lineage_refs: [],
      proof_refs: ["reconcile:contradiction"],
      privacy: "sanitized",
    },
  ],
  entities: [
    {
      entity_id: "entity-admin-home-lifecycle",
      kind: "project",
      title: "canonical admin home and conversation lifecycle",
      summary:
        "one current attention projection with searchable, reversible history.",
      lifecycle: "open",
      owner: "chief/anipotts.com",
      owner_state: "current",
      contradiction_refs: [],
      source_ids: [
        "source-codex-admin-home",
        "source-chatgpt-lifecycle-export",
        "source-github-pr-244",
      ],
      outcome_ids: [],
      attention_ids: ["attention-admin-home-review"],
      updated_at: NOW,
      archived_at: null,
    },
    {
      entity_id: "entity-infra-adapter-contract",
      kind: "task",
      title: "sanitized lifecycle adapter contract",
      summary:
        "chief infra owns source inventory and reconciliation fixture parity.",
      lifecycle: "open",
      owner: "chief/infra",
      owner_state: "current",
      contradiction_refs: [],
      source_ids: ["source-infra-adapter-handoff"],
      outcome_ids: [],
      attention_ids: [],
      updated_at: "2026-07-22T15:30:00.000Z",
      archived_at: null,
    },
    {
      entity_id: "entity-retired-site-topology",
      kind: "reference",
      title: "retired four-lane site topology",
      summary:
        "preserved branches and handoffs remain evidence after consolidation.",
      lifecycle: "completed",
      owner: "chief/anipotts.com",
      owner_state: "current",
      contradiction_refs: [],
      source_ids: ["source-retired-topology-handoff"],
      outcome_ids: ["outcome-retired-topology"],
      attention_ids: [],
      updated_at: "2026-07-20T18:00:00.000Z",
      archived_at: null,
    },
    {
      entity_id: "entity-legacy-index-review",
      kind: "reference",
      title: "legacy local index review",
      summary: "completed inventory with an unavailable latest reconciliation.",
      lifecycle: "completed",
      owner: "chief/anipotts.com",
      owner_state: "current",
      contradiction_refs: [],
      source_ids: ["source-unavailable-legacy-index"],
      outcome_ids: ["outcome-legacy-index"],
      attention_ids: [],
      updated_at: "2026-07-19T12:00:00.000Z",
      archived_at: null,
    },
    {
      entity_id: "entity-conflicting-archive-review",
      kind: "reference",
      title: "conflicting archive review",
      summary:
        "completion evidence is retained while reconciliation disagrees.",
      lifecycle: "completed",
      owner: "chief/anipotts.com",
      owner_state: "current",
      contradiction_refs: ["reconcile:contradiction"],
      source_ids: ["source-conflicting-archive-record"],
      outcome_ids: ["outcome-conflicting-archive"],
      attention_ids: [],
      updated_at: "2026-07-21T12:00:00.000Z",
      archived_at: null,
    },
  ],
  outcomes: [
    {
      outcome_id: "outcome-retired-topology",
      entity_id: "entity-retired-site-topology",
      status: "completed",
      summary: "ownership consolidated to chief and writing tasks.",
      proof_refs: ["handoff:2026-07-20-anipotts-com-consolidation"],
      recorded_at: "2026-07-20T18:00:00.000Z",
    },
    {
      outcome_id: "outcome-legacy-index",
      entity_id: "entity-legacy-index-review",
      status: "completed",
      summary: "last-good inventory was recorded before the adapter failed.",
      proof_refs: ["probe:last-good-inventory"],
      recorded_at: "2026-07-19T12:00:00.000Z",
    },
    {
      outcome_id: "outcome-conflicting-archive",
      entity_id: "entity-conflicting-archive-review",
      status: "completed",
      summary:
        "one source reported completion but contradiction remains unresolved.",
      proof_refs: ["reconcile:contradiction"],
      recorded_at: "2026-07-21T12:00:00.000Z",
    },
  ],
  attention: [
    {
      attention_id: "attention-admin-home-review",
      entity_id: "entity-admin-home-lifecycle",
      attention_kind: "review",
      status: "current",
      reason: "review the exact local slice before any migration or deploy.",
      owner: "chief/anipotts.com",
      source_ids: [
        "source-codex-admin-home",
        "source-chatgpt-lifecycle-export",
      ],
      updated_at: NOW,
    },
  ],
  history: [
    {
      history_id: "history-admin-home-converged",
      entity_id: "entity-admin-home-lifecycle",
      kind: "linked",
      summary:
        "codex work, chat history, and preserved pr evidence converged on one entity.",
      source_ids: [
        "source-codex-admin-home",
        "source-chatgpt-lifecycle-export",
        "source-github-pr-244",
      ],
      proof_refs: ["git:tag/preserve-admin-244-30976f0-20260720"],
      receipt_id: null,
      recorded_at: NOW,
    },
    {
      history_id: "history-site-topology-completed",
      entity_id: "entity-retired-site-topology",
      kind: "completed",
      summary:
        "the retired control, public, admin, and quality lanes were consolidated.",
      source_ids: ["source-retired-topology-handoff"],
      proof_refs: ["handoff:2026-07-20-anipotts-com-consolidation"],
      receipt_id: null,
      recorded_at: "2026-07-20T18:00:00.000Z",
    },
  ],
  proposals: [],
  receipts: [],
  errors: [],
};
