name = "anipotts-admin"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
account_id = "0f856093bdcd34a7da1bde5ee4385163"
main = ".open-next/worker.js"
workers_dev = false

# Custom domain
[[routes]]
pattern = "admin.anipotts.com/*"
zone_id = "d56476e2905a2a19ad86aaa4b7c719c2"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Non-secret env vars available at runtime
[vars]
CF_ACCOUNT_ID = "0f856093bdcd34a7da1bde5ee4385163"

# D1 database binding
[[d1_databases]]
binding = "DB"
database_name = "anipotts-db"
database_id = "a8aadf73-bbf4-447c-97db-cb3e50b4e26f"
