import { defineConfig } from "tsup";

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "db/index": "src/db/index.ts",
    "utils/index": "src/utils/index.ts",
    "feature-flags/index": "src/feature-flags/index.ts",
    "data/index": "src/data/index.ts",
    "admin/index": "src/admin/index.ts",
    "admin-control/index": "src/admin-control/index.ts",
    "metrics/index": "src/metrics/index.ts",
    "status/index": "src/status/index.ts",
    "typefully/index": "src/typefully/index.ts",
    "cms/index": "src/cms/index.ts",
    "validation/index": "src/validation/index.ts",
    "money/index": "src/money/index.ts",
    "code/index": "src/code/index.ts",
    "ops/index": "src/ops/index.ts",
    "services/index": "src/services/index.ts",
    "mini/index": "src/mini/index.ts",
    "mini/stream": "src/mini/stream.ts",
    "analytics/index": "src/analytics/index.ts",
    "quantercise/index": "src/quantercise/index.ts",
    env: "src/env.ts",
  },
  format: ["esm"],
  dts: true,
  splitting: true,
  sourcemap: false,
  external: ["react"],
});
