export {
  DEFAULT_CMS_PROJECTS,
  DEFAULT_CMS_WRITING,
  DEFAULT_HOMEPAGE_CONTENT,
  DEFAULT_MAKING_INDEX_CONTENT,
  DEFAULT_WORK_INDEX_CONTENT,
  DEFAULT_NEWSLETTER_CONTENT,
  DEFAULT_NEWSLETTER_ARCHIVE_CONTENT,
  DEFAULT_ORCHESTRATING_CONTENT,
  DEFAULT_PROJECTS_INDEX_CONTENT,
  DEFAULT_SYSTEMS_CONTENT,
  DEFAULT_WRITING_INDEX_CONTENT,
  HOME_SECTION_ORDER,
  PUBLIC_CONTENT_SOURCE_HASH,
} from "./generated.js";

export const HOMEPAGE_FIELD_LIMITS = {
  label: 80,
  heading: 160,
  subheading: 500,
  paragraph: 1200,
  linkLabel: 80,
  linkHref: 300,
  mentionKey: 80,
  mentionLabel: 120,
  mentionAsset: 220,
  slug: 120,
  proofTitle: 120,
  proofDetail: 360,
  limitMin: 1,
  limitMax: 12,
} as const;

export const CMS_TEXT_LIMITS = {
  slug: 120,
  title: 160,
  status: 40,
  year: 40,
  range: 80,
  tag: 40,
  summary: 600,
  body: 12000,
  linkLabel: 80,
  linkUrl: 300,
  newsletterHeadline: 160,
  newsletterDeck: 600,
  newsletterFooter: 1200,
  sender: 120,
} as const;
